### ISSUE TITLE
Guidance on usage with trusted types

### ISSUE THREAD

**Issue by rictic** [googleinterns/tsec#10]
I tried to use tsec in lit-html and ran into a couple of issues:

```
src/lit-html.ts:219:12 - error TS21228: Creating a Trusted Types policy requires a security review.

219     return window.trustedTypes.createPolicy('lit-html', policy);
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/lit-html.ts:371:5 - error TS21228: Assigning directly to Element#innerHTML can result in XSS vulnerabilities.

371     this.__element.innerHTML = policy.createHTML(html + this.__strings[l]);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Is there a facility to run tsec with an allowlist or similar?

**Comment by koto** [comment]
cc @Siegrift @uraj

**Comment by uraj** [comment]
Sorry for the late reply. Yes, you can configure exemptions on a per-rule and per-file basis.

Add the following entry into the `tsconfig.json` of your project: `'conformanceExemptionPath': './conformance_exemption.json'`, and create a file named `conformance_exemption.json` in the same folder of your tsconfig.json.

In `conformance_exemption.json`, configure the exemptions like this:
```json
{
  "ban-trustedtypes-createpolicy": ['src/lit-html.ts'],
  "ban-element-innerhtml-assignments": ['src/lit-html.ts'],
}
```

We will update our README shortly.
