### ISSUE TITLE
Casting tricks don't work

### ISSUE THREAD

**Issue by jrieken** [googleinterns/tsec#18]
* get https://github.com/microsoft/vscode
* run `yarn && yarn tsec-compile-check`
* :bug: you see errors being reported for things that should be ok, like usages of  `trustedOrString as unknown as string`

This is an example (there are a few more) where tsec complaints although it shouldn't

https://github.com/microsoft/vscode/blob/5f569de4cd54e43d0239e339b5f4e60f367cf75f/src%2Fvs%2Fworkbench%2Fcontrib%2Fnotebook%2Fbrowser%2Fview%2Frenderers%2FcellRenderer.ts#L595

**Comment by Siegrift** [comment]
This is intended.

Variable `linesHtml` has type `string | TrustedHTML` so you only need casting to `string`.
Assignment `element.innerHTML = linesHtml as string;` works properly.

The reason for this is, that the casting trick through `unknown` requires the variable type to be **exactly** `TrustedHTML` *(and it's an union in your case)*.

**Comment by jrieken** [comment]
> Assignment element.innerHTML = linesHtml as string; works properly.

Pretty sure that I have tried this but without success. Tho, I might have been on a wrong version of `tsec` - the yarn upgrade trick seems to be buggy and we are kinda desperate for https://github.com/googleinterns/tsec/issues/17. Folks keep getting a wrong version of tsec and aren't happy with tsec at all

**Comment by engelsdamien** [comment]
I think I figured it out. The latest version of tsec seems to have lost the postinstall script that allows it to build, so even with the upgrade, it is still running old code. I've raised the issue internally and we'll work on a fix.

**Comment by jrieken** [comment]
Oh, the explains a lot
