### ISSUE TITLE
No support for project references?

### ISSUE THREAD

**Issue by jrieken** [googleinterns/tsec#19]
* use https://github.com/xtermjs/xterm.js/blob/master/tsconfig.all.json
* run `tsec` via `node node_modules/tsec/bin/tsec -p ./tsconfig.all.json --noEmit`
* :bug: the error below happens

```
root@codespaces_234666:~/workspace/xterm.js# node node_modules/tsec/bin/tsec -p ./tsconfig.all.json --noEmit
tsec: Cannot find project configuration.
root@codespaces_234666:~/workspace/xterm.js# 
```

**Comment by uraj** [comment]
Hi, we just added support for project references. You use tsec the same way as tsc, like `node node_modules/tsec/bin/tsec -b ./tsconfig.all.json`
