### ISSUE TITLE
Exemptions not working?

### ISSUE THREAD

**Issue by jrieken** [googleinterns/tsec#21]
* get vscode sources
* run `yarn tsec-compile-check`
* you see errors for policy creation which should be exempted according to https://github.com/microsoft/vscode/blob/a5a0c1527d16edc72f42467a5de4039b38c0f91b/src/tsec.exemptions.json#L2

**Comment by uraj** [comment]
There was a bug in the code finding the correct tsconfig.json. It should have been fixed now.

**Comment by jrieken** [comment]
Thanks. This is working now
